fail_fast: false
exclude: |
    (?x)^(
        tests/data/.*
    )$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.5
    hooks:
      # Run the linter.
      - id: ruff
        args: ["--select", "I", "--fix"]
      # Run the formatter.
      - id: ruff-format
  - repo: local
    hooks:
    -   id: pyupgrade
        name: pyupgrade
        entry: poetry run pyupgrade --py38-plus
        language: python
        types: [python]
        pass_filenames: true
