# Generated by Django 2.2.12 on 2020-05-01 16:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_peeringdb", "0006_net_operational"),
    ]

    operations = []
