# Generated by Django 3.2.7 on 2022-12-09 13:49

import django.core.validators
import django.db.models.deletion
import django_countries.fields
import django_inet.models
from django.db import migrations, models

import django_peeringdb.models.abstract


class Migration(migrations.Migration):

    dependencies = [
        ("django_peeringdb", "0022_carriers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ixlan",
            name="mtu",
            field=models.PositiveIntegerField(
                choices=[(1500, "1500"), (9000, "9000")],
                default=1500,
                verbose_name="MTU",
            ),
        ),
    ]
