# Generated by Django 3.2.7 on 2024-01-09 11:57

from django.db import migrations

import django_peeringdb.fields


class Migration(migrations.Migration):
    dependencies = [
        ("django_peeringdb", "0027_auto_20230804_1414"),
    ]

    operations = [
        migrations.AddField(
            model_name="network",
            name="info_types",
            field=django_peeringdb.fields.MultipleChoiceField(
                blank=True,
                choices=[
                    ("NSP", "NSP"),
                    ("Content", "Content"),
                    ("Cable/DSL/ISP", "Cable/DSL/ISP"),
                    ("Enterprise", "Enterprise"),
                    ("Educational/Research", "Educational/Research"),
                    ("Non-Profit", "Non-Profit"),
                    ("Route Server", "Route Server"),
                    ("Network Services", "Network Services"),
                    ("Route Collector", "Route Collector"),
                    ("Government", "Government"),
                ],
                max_length=255,
                verbose_name="Network Types",
            ),
        ),
    ]
