# Generated by Django 3.2.7 on 2024-01-09 12:46

from django.db import migrations

import django_peeringdb.fields


class Migration(migrations.Migration):
    dependencies = [
        ("django_peeringdb", "0028_auto_20240109_1157"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="available_voltage_services",
            field=django_peeringdb.fields.MultipleChoiceField(
                blank=True,
                choices=[
                    ("48 VDC", "48 VDC"),
                    ("400 VAC", "400 VAC"),
                    ("480 VAC", "480 VAC"),
                ],
                help_text="The alternating current voltage available to users of the facility either directly from the landlord or delivered by the utility separately.",
                max_length=255,
                null=True,
                verbose_name="Available Voltage Services",
            ),
        ),
    ]
