# Generated by Django 3.2.7 on 2024-02-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_peeringdb", "0029_auto_20240109_1246"),
    ]

    operations = [
        migrations.AddField(
            model_name="networkixlan",
            name="bfd_support",
            field=models.BooleanField(default=False, verbose_name="BFD support"),
        )
    ]
