# Generated by Django 5.2.6 on 2026-02-10 13:17

import django_peeringdb.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_peeringdb", "0037_alter_networkfacility_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="available_voltage_services",
            field=django_peeringdb.fields.MultipleChoiceField(
                blank=True,
                choices=[
                    ("No Power", "No Power"),
                    ("48 VDC", "48 VDC"),
                    ("400 VAC", "400 VAC"),
                    ("480 VAC", "480 VAC"),
                ],
                help_text="The alternating current voltage available to users of the facility either directly from the landlord or delivered by the utility separately.",
                max_length=255,
                null=True,
                verbose_name="Available Voltage Services",
            ),
        ),
    ]
