# Generated by Django 5.2.14 on 2026-05-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_peeringdb", "0038_alter_facility_available_voltage_services"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networkixlan",
            name="speed",
            field=models.PositiveIntegerField(verbose_name="Capacity (mbit/sec)"),
        ),
    ]
