# Generated by Django 5.2.16 on 2026-08-15 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_peeringdb", "0039_alter_networkixlan_speed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="network",
            name="irr_as_set",
            field=models.CharField(
                blank=True,
                help_text="Reference to an AS-SET in Internet Routing Registry (IRR)",
                max_length=255,
                verbose_name="IRR as-set",
            ),
        ),
    ]
