# Generated by Django 5.2.16 on 2026-08-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_peeringdb", "0040_alter_network_irr_as_set"),
    ]

    operations = [
        migrations.AddField(
            model_name="network",
            name="meta",
            field=models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
        ),
        migrations.AddField(
            model_name="networkixlan",
            name="meta",
            field=models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
        ),
    ]
