# Generated by Django 2.2.12 on 2020-09-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_peeringdb", "0011_ixlan_ixf_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="network",
            name="fac_set",
            field=models.ManyToManyField(
                related_name="net_set",
                through="django_peeringdb.NetworkFacility",
                to="django_peeringdb.Facility",
                verbose_name="Facility",
            ),
        ),
        migrations.AddField(
            model_name="network",
            name="ixlan_set",
            field=models.ManyToManyField(
                related_name="net_set",
                through="django_peeringdb.NetworkIXLan",
                to="django_peeringdb.IXLan",
                verbose_name="Internet Exchange LAN",
            ),
        ),
    ]
